export const affirmationData = [
  { affirmation: 'Life is beautiful.' },
  { affirmation: 'I am connected to nature.' },
  { affirmation: 'I am fearless.' },
  { affirmation: 'I am successful.' },
  { affirmation: 'I know who I am.' },
  { affirmation: 'I am aware.' },
  { affirmation: 'This day is a blessing that I will not waste.' },
  { affirmation: 'I will face my fears head on.' },
  { affirmation: 'I surround myself with positive energy.' },
  { affirmation: 'Negative self talk has no place in my life.' },
  { affirmation: 'I patiently allow my body to heal.' },
  { affirmation: 'I treat others fairly and with respect.' },
  { affirmation: 'My negative thoughts of myself are gone.' },
  { affirmation: 'I control my day.' },
  { affirmation: 'I face the day with calm and patience.' },
  { affirmation: 'I am whole.' },
  { affirmation: 'I can go with the flow.' },
  { affirmation: 'If I fail, I will fail forward.' },
  { affirmation: 'Where others see challenge, I see opportunity.' },
  { affirmation: 'I am not afraid of obstacles.' },
  { affirmation: 'Calm is my main state of being.' },
  { affirmation: 'I am healthy. I am brilliant. I am at peace.' },
  { affirmation: 'My confidence is limitless.' },
  { affirmation: 'I choose what I become.' },
  { affirmation: 'My life is special to me.' },
  { affirmation: 'I am calm and in control of my emotions.' },
  { affirmation: 'I am not my mistakes.' },
  { affirmation: 'I am enough.' },
  { affirmation: 'I allow myself to be fully loved.' },
  { affirmation: 'I will continue to learn and grow.' },
  { affirmation: 'I am fully committed to achieving my goals.' },
  { affirmation: 'I will be the best that I can be.' },
  { affirmation: 'I am wise.' },
  { affirmation: 'I stand by my decisions. They are sound and reasoned.' },
  { affirmation: 'I believe in my skills and abilities.' },
  { affirmation: 'What I give is what I receive.' },
  { affirmation: 'I am filled with positive energy.' },
  { affirmation: "I've survived all the difficult moments of my past." },
  { affirmation: 'I choose hope over fear.' },
  { affirmation: 'My body is in perfect balance.' },
  { affirmation: 'I have abundant energy.' },
  { affirmation: 'I am not alone in my struggles.' },
  { affirmation: "I'm happy with my accomplishments." },
  { affirmation: 'I deserve love, compassion and empathy.' },
  { affirmation: 'I give love.' },
  { affirmation: 'I am patient.' },
  { affirmation: 'I deserve peace.' },
  { affirmation: 'I make positive choices for myself.' },
  { affirmation: 'I choose to love myself completely.' },
  { affirmation: 'I am in the now.' },
  { affirmation: 'I am confident.' },
  { affirmation: 'I am happy and healthy.' },
  { affirmation: 'I can and I will.' },
  { affirmation: 'I will change and adjust as needed.' },
  { affirmation: 'I trust the guidance of the Universe.' },
  {
    affirmation:
      'I face the day with strength in my heart and clarity in my mind.'
  },
  { affirmation: 'I will be okay.' },
  { affirmation: 'I love myself unconditionally.' },
  { affirmation: 'I am wanted.' },
  { affirmation: 'I radiate beauty and charm.' },
  { affirmation: 'I let go of anything not for my highest good.' },
  { affirmation: 'I am courageous and will stand up for myself.' },
  { affirmation: "It's not their job to like me, it's mine." },
  { affirmation: 'I will not compare myself to others. I am unique.' },
  { affirmation: 'I am content.' },
  { affirmation: 'Today I am my own superhero.' },
  { affirmation: "I am allowed to say 'no' to others and 'yes' to myself." },
  { affirmation: 'Every breath I take fills my soul with ease.' },
  { affirmation: "I don't need to prove myself." },
  { affirmation: 'I am above negative thoughts and low actions.' },
  { affirmation: 'I approve of myself.' },
  { affirmation: 'I have everything I need.' },
  { affirmation: 'I accept myself unconditionally.' },
  { affirmation: 'I will find a way.' },
  {
    affirmation:
      'I will search for the good that comes, even in bad situations.'
  },
  { affirmation: 'I deserve to be loved.' },
  { affirmation: 'I am independent.' },
  { affirmation: 'I am strong.' },
  { affirmation: 'I am at peace with the past, present, and future.' },
  { affirmation: 'My feelings are valid.' },
  { affirmation: 'All is well in my world.' },
  { affirmation: 'I will be open to new ideas.' },
  { affirmation: 'I am excited about today.' },
  { affirmation: 'I choose to be calm and at peace.' },
  { affirmation: 'Success is in my future.' },
  { affirmation: 'I believe in myself and so do others.' },
  { affirmation: 'There are no limits on what I can achieve today.' },
  { affirmation: 'Others will not take advantage of me.' },
  { affirmation: 'All situations are temporary.' },
  { affirmation: 'No one can make me feel inferior.' },
  { affirmation: 'I am present.' },
  { affirmation: "I know what I'm doing." },
  { affirmation: 'I am loved.' },
  { affirmation: 'I deserve rest and relaxation.' },
  { affirmation: 'I act with courage and confidence.' },
  { affirmation: 'I learn from my failures.' },
  { affirmation: "I'm getting strong every day." },
  { affirmation: 'I will speak with confidence.' },
  { affirmation: 'My life has just begun.' },
  { affirmation: 'This day is full of potential.' },
  { affirmation: 'I am blessed with a wonderful family.' },
  { affirmation: 'My life overflows with opportunity.' },
  { affirmation: 'My imperfections make me unique and special.' },
  { affirmation: 'I do the best that I can.' },
  { affirmation: 'Today I will be authentic.' },
  { affirmation: 'I am creating my life exactly as I want it.' },
  { affirmation: 'I do not fear making mistakes.' },
  { affirmation: 'The only person who can defeat me is myself.' },
  { affirmation: 'I am my best chance for success.' },
  { affirmation: 'I matter.' },
  { affirmation: 'I am a leader.' },
  { affirmation: 'I can do anything I set my mind to.' },
  { affirmation: 'I will work with enthusiasm and confidence.' },
  { affirmation: 'I can find happiness in myself.' },
  { affirmation: 'I am destined for success.' },
  { affirmation: 'I will not take negativity personally.' },
  {
    affirmation:
      'Be kind to your mind. Treat your mind as if it were the mind of someone you love.'
  },
  { affirmation: 'There is no wrong decision.' },
  { affirmation: 'Today I will center myself in peace.' },
  { affirmation: 'I am my source of motivation.' },
  { affirmation: "I'm not afraid to be wrong." },
  { affirmation: 'I am mindful.' },
  { affirmation: "I will say 'no' when I do not have the time." },
  { affirmation: 'I have the courage to say no.' },
  { affirmation: 'I am willing to explore new and uncharted territory.' },
  { affirmation: 'I desire to learn new things.' },
  { affirmation: 'I forgive those who have harmed me in the past.' },
  { affirmation: 'I inspire others.' },
  { affirmation: 'I have the power I need to create the success I desire.' },
  { affirmation: 'I am a gift to this world.' },
  { affirmation: 'My opinion matters.' },
  { affirmation: 'I am fulfilled.' },
  { affirmation: 'My only limit is myself.' },
  { affirmation: "I do not focus on 'what if'." },
  { affirmation: 'I am where I need to be.' },
  { affirmation: 'I am on the best path for me.' },
  { affirmation: 'I am grateful for what I have.' },
  { affirmation: 'I acknowledge my own self-worth.' },
  { affirmation: 'I am focused, persistent, and will not quit.' },
  { affirmation: 'I will take action and get things accomplished.' },
  { affirmation: 'I listen to others with intention.' },
  { affirmation: 'I am constantly improving.' },
  { affirmation: 'Today I am optimistic.' },
  { affirmation: 'I can do this.' },
  { affirmation: 'I honor who I am.' },
  { affirmation: 'I embrace positivity and optimism.' },
  { affirmation: 'I am good enough.' },
  { affirmation: 'Laughter lightens my load.' },
  { affirmation: 'My life is made for joy.' },
  { affirmation: "Today I will not stress over things I can't control." },
  { affirmation: 'I am who I want to be.' },
  { affirmation: 'I choose to be happy.' },
  { affirmation: 'I know my worth.' },
  { affirmation: 'I choose to exercise regularly.' },
  { affirmation: 'Today I will accomplish great things.' },
  { affirmation: 'I will achieve my goals.' },
  { affirmation: 'I dare to be different.' },
  { affirmation: 'I am worthy of everything good in life.' },
  { affirmation: 'I express my creativity.' },
  { affirmation: 'I choose to be positive.' },
  { affirmation: 'I was not made to give up,' },
  { affirmation: 'I possess the qualities I need to succeed.' },
  { affirmation: 'I am the architect of my life.' }
];
