# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PresMo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PresMo


  target 'PresMoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PresMo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PresMo-tvOS

  target 'PresMo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
